/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPainelRouteImport } from './routes/_auth.painel'
import { Route as AuthPainelPerfilRouteImport } from './routes/_auth.painel.perfil'
import { Route as AuthPainelPedidosRouteImport } from './routes/_auth.painel.pedidos'
import { Route as AuthPainelNovoPedidoRouteImport } from './routes/_auth.painel.novo-pedido'
import { Route as AuthPainelDashboardRouteImport } from './routes/_auth.painel.dashboard'
import { Route as AuthPainelCardapioRouteImport } from './routes/_auth.painel.cardapio'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPainelRoute = AuthPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPainelPerfilRoute = AuthPainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthPainelRoute,
} as any)
const AuthPainelPedidosRoute = AuthPainelPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthPainelRoute,
} as any)
const AuthPainelNovoPedidoRoute = AuthPainelNovoPedidoRouteImport.update({
  id: '/novo-pedido',
  path: '/novo-pedido',
  getParentRoute: () => AuthPainelRoute,
} as any)
const AuthPainelDashboardRoute = AuthPainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthPainelRoute,
} as any)
const AuthPainelCardapioRoute = AuthPainelCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AuthPainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/login': typeof LoginRoute
  '/painel': typeof AuthPainelRouteWithChildren
  '/painel/cardapio': typeof AuthPainelCardapioRoute
  '/painel/dashboard': typeof AuthPainelDashboardRoute
  '/painel/novo-pedido': typeof AuthPainelNovoPedidoRoute
  '/painel/pedidos': typeof AuthPainelPedidosRoute
  '/painel/perfil': typeof AuthPainelPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/login': typeof LoginRoute
  '/painel': typeof AuthPainelRouteWithChildren
  '/painel/cardapio': typeof AuthPainelCardapioRoute
  '/painel/dashboard': typeof AuthPainelDashboardRoute
  '/painel/novo-pedido': typeof AuthPainelNovoPedidoRoute
  '/painel/pedidos': typeof AuthPainelPedidosRoute
  '/painel/perfil': typeof AuthPainelPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/login': typeof LoginRoute
  '/_auth/painel': typeof AuthPainelRouteWithChildren
  '/_auth/painel/cardapio': typeof AuthPainelCardapioRoute
  '/_auth/painel/dashboard': typeof AuthPainelDashboardRoute
  '/_auth/painel/novo-pedido': typeof AuthPainelNovoPedidoRoute
  '/_auth/painel/pedidos': typeof AuthPainelPedidosRoute
  '/_auth/painel/perfil': typeof AuthPainelPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/login'
    | '/painel'
    | '/painel/cardapio'
    | '/painel/dashboard'
    | '/painel/novo-pedido'
    | '/painel/pedidos'
    | '/painel/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/login'
    | '/painel'
    | '/painel/cardapio'
    | '/painel/dashboard'
    | '/painel/novo-pedido'
    | '/painel/pedidos'
    | '/painel/perfil'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/ajuda'
    | '/login'
    | '/_auth/painel'
    | '/_auth/painel/cardapio'
    | '/_auth/painel/dashboard'
    | '/_auth/painel/novo-pedido'
    | '/_auth/painel/pedidos'
    | '/_auth/painel/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/painel': {
      id: '/_auth/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthPainelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/painel/perfil': {
      id: '/_auth/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthPainelPerfilRouteImport
      parentRoute: typeof AuthPainelRoute
    }
    '/_auth/painel/pedidos': {
      id: '/_auth/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof AuthPainelPedidosRouteImport
      parentRoute: typeof AuthPainelRoute
    }
    '/_auth/painel/novo-pedido': {
      id: '/_auth/painel/novo-pedido'
      path: '/novo-pedido'
      fullPath: '/painel/novo-pedido'
      preLoaderRoute: typeof AuthPainelNovoPedidoRouteImport
      parentRoute: typeof AuthPainelRoute
    }
    '/_auth/painel/dashboard': {
      id: '/_auth/painel/dashboard'
      path: '/dashboard'
      fullPath: '/painel/dashboard'
      preLoaderRoute: typeof AuthPainelDashboardRouteImport
      parentRoute: typeof AuthPainelRoute
    }
    '/_auth/painel/cardapio': {
      id: '/_auth/painel/cardapio'
      path: '/cardapio'
      fullPath: '/painel/cardapio'
      preLoaderRoute: typeof AuthPainelCardapioRouteImport
      parentRoute: typeof AuthPainelRoute
    }
  }
}

interface AuthPainelRouteChildren {
  AuthPainelCardapioRoute: typeof AuthPainelCardapioRoute
  AuthPainelDashboardRoute: typeof AuthPainelDashboardRoute
  AuthPainelNovoPedidoRoute: typeof AuthPainelNovoPedidoRoute
  AuthPainelPedidosRoute: typeof AuthPainelPedidosRoute
  AuthPainelPerfilRoute: typeof AuthPainelPerfilRoute
}

const AuthPainelRouteChildren: AuthPainelRouteChildren = {
  AuthPainelCardapioRoute: AuthPainelCardapioRoute,
  AuthPainelDashboardRoute: AuthPainelDashboardRoute,
  AuthPainelNovoPedidoRoute: AuthPainelNovoPedidoRoute,
  AuthPainelPedidosRoute: AuthPainelPedidosRoute,
  AuthPainelPerfilRoute: AuthPainelPerfilRoute,
}

const AuthPainelRouteWithChildren = AuthPainelRoute._addFileChildren(
  AuthPainelRouteChildren,
)

interface AuthRouteChildren {
  AuthPainelRoute: typeof AuthPainelRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPainelRoute: AuthPainelRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AjudaRoute: AjudaRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
